blueprint:
  name: Turn Off After Inactivity
  description: >
    Turns off lights or other devices after a motion or occupancy sensor
    has been inactive for a specified duration.
  domain: automation
  input:
    trigger_sensor:
      name: Motion or Occupancy Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - motion
            - occupancy

    inactivity_duration:
      name: Inactivity Duration (hours)
      description: Time the sensor must remain inactive before triggering the action
      default: 3
      selector:
        number:
          min: 0.1
          max: 24
          step: 0.1
          unit_of_measurement: hours
          mode: slider

    action_target:
      name: Entity to Turn Off
      description: The entity to turn off (e.g., light, switch)
      selector:
        target:

    only_if_on:
      name: Only Turn Off If Entity Is On?
      default: true
      selector:
        boolean:

mode: single

trigger:
  - platform: state
    entity_id: !input trigger_sensor
    to: "off"
    for:
      hours: !input inactivity_duration

condition:
  - condition: or
    conditions:
      - condition: template
        value_template: "{{ not input.only_if_on }}"
      - condition: state
        entity_id: !input action_target
        state: "on"

action:
  - service: homeassistant.turn_off
    target: !input action_target
