blueprint:
  name: Auto Turn Off Lights After Vacancy (Multi-Sensor)
  description: >
    Turns off selected lights after ALL chosen binary_sensors (motion/occupancy) have
    been clear (off) for the entire delay. Works with PIR (e.g., Third Reality 3RMS16BZ),
    mmWave occupancy, etc.
  domain: automation
  input:
    presence_sensors:
      name: Motion/Occupancy Sensors
      description: Select one or more binary_sensors used to determine vacancy
      selector:
        entity:
          domain: binary_sensor
          multiple: true
    lights:
      name: Light(s)
      description: Select one or more light
