blueprint:
  name: Auto Turn Off Lights After No Motion/Occupancy
  description: Turns off selected lights if no motion/occupancy is detected for a set period of time.
  domain: automation
  input:
    presence_sensor:
      name: Motion/Occupancy Sensor
      description: Choose a binary_sensor with device class motion or occupancy
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - motion
            - occupancy
    target_light:
      name: Light
      description: The light or light group to turn off
      selector:
        entity:
          domain: light
    delay_time:
      name: Delay (No Motion/Occupancy Time)
      description: Time to wait after no motion/occupancy before turning off the light
      default: 02:00:00
      selector:
        duration: {}

mode: single

trigger:
  - platform: state
    entity_id: !input presence_sensor
    to: "off"
    for: !input delay_time

condition:
  - condition: state
    entity_id: !input target_light
    state: "on"

action:
  - service: light.turn_off
    target:
      entity_id: !input target_light
