blueprint:
  name: Auto Turn Off Lights After Idle (Single Sensor)
  description: >
    Uses one motion/occupancy binary_sensor. When it stays OFF (no activity)
    for the set delay, turn off the selected light(s).
  domain: automation

  input:
    trigger_sensor:
      name: Motion/Occupancy Sensor
      description: A single binary_sensor that goes ON when active and OFF when idle
      selector:
        entity:
          domain: binary_sensor
          multiple: false
    lights:
      name: Light(s)
      description: One or more light entities to turn off
      selector:
        entity:
          domain: light
          multiple: true
    delay_time:
      name: Idle Delay
      description: How long the sensor must be OFF before turning off the lights
      default: 02:00:00
      selector:
        duration: {}

mode: restart

trigger:
  - platform: state
    entity_id: !input trigger_sensor
    to: "off"
    for: !input delay_time

action:
  - service: light.turn_off
    target:
      entity_id: !input lights
