blueprint:
  name: Motion Sensor Inactivity Trigger
  description: Perform actions when no motion is detected for a specified duration.
  domain: automation
  input:
    motion_sensor:
      name: Motion Sensor
      description: The motion sensor to monitor.
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    duration:
      name: Inactivity Duration
      description: Time to wait after last motion before triggering actions.
      default: 00:05:00
      selector:
        duration:
    actions:
      name: Actions to Perform
      description: Actions to run when no motion is detected for the specified duration.
      selector:
        action:

trigger:
  - platform: state
    entity_id: !input motion_sensor
    to: 'off'
    for: !input duration

action: !input actions

mode: restart
